services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: abc123
      MYSQL_DATABASE: cms
      MYSQL_USER: cms
      MYSQL_PASSWORD: abc123
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql_data:/var/lib/mysql
